# Generated by Django 5.0.4 on 2024-04-21 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0005_customuser_date_joined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomMalumotTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name="Ma'lumot turi")),
            ],
        ),
        migrations.CreateModel(
            name='DiplomMuassasaTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Muassasa turi')),
            ],
        ),
        migrations.CreateModel(
            name='Kurslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_nomi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diplom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplom_seriya', models.CharField(max_length=255)),
                ('muassasa_nomi', models.TextField()),
                ('tugatgan_yili', models.CharField(max_length=255)),
                ('diplom_fayl', models.FileField(upload_to='diplomlar/')),
                ('tugatgan_tumani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.district', verbose_name='Tuman/Shahari')),
                ('tugatgan_viloyati', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.region', verbose_name='Viloyati')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diplom', to=settings.AUTH_USER_MODEL)),
                ('malumot_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.diplommalumotturi', verbose_name="Ma'lumot turi")),
                ('muassasa_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.diplommuassasaturi', verbose_name='Muassasa turi')),
            ],
        ),
        migrations.CreateModel(
            name='PerevodDiplom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universitet_nomi', models.TextField()),
                ('transkript', models.FileField(upload_to='trasnkriptlar/')),
                ('davlat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.country', verbose_name='Davlat')),
                ('topshiradigan_kursi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diplom_app.kurslar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perevod_diplom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
