# Generated by Django 5.0.4 on 2024-04-18 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('second_name', models.CharField(max_length=100, verbose_name='Otasining ismi')),
                ('third_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('passport_number', models.CharField(max_length=9, verbose_name='Pasport raqami')),
                ('jshshir', models.CharField(max_length=14, unique=True, verbose_name='JSHSHIR')),
                ('image', models.ImageField(upload_to='abituriyent/images/', verbose_name='Abituriyent rasmi(3x4)')),
                ('gender', models.CharField(choices=[('E', 'Erkak'), ('A', 'Ayol')], max_length=1, verbose_name='Jins')),
                ('country', models.CharField(max_length=100, verbose_name='Mamlakat')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman')),
                ('home_address', models.CharField(max_length=255, verbose_name='Uy manzili')),
                ('passport_file', models.FileField(upload_to='abituriyent/passports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passport', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passport',
                'verbose_name_plural': 'Passportlar',
            },
        ),
    ]
