# Generated by Django 5.0.4 on 2024-04-21 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0005_customuser_date_joined'),
        ('course_app', '0002_alter_yonalish_nomi'),
        ('diplom_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name='Holat nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_perevod', models.BooleanField(default=False, verbose_name="O'tkazilganmi?")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('diplom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diplom_app.diplom', verbose_name='Diplom')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.filial', verbose_name='Filial')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.passport', verbose_name='Pasport')),
                ('perevod_diplom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diplom_app.perevoddiplom', verbose_name="Diplomni o'tkazish")),
                ('talim_shakli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.talimshakli', verbose_name="Ta'lim shakli")),
                ('talim_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.talimturi', verbose_name="Ta'lim turi")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.yonalish', verbose_name="Yo'nalish")),
                ('apply_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply_app.applystatus', verbose_name='Ariza holati')),
            ],
        ),
    ]
