# Generated by Django 5.0.4 on 2024-04-20 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Filial nomi')),
            ],
        ),
        migrations.CreateModel(
            name='TalimShakli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name="Ta'lim shakli nomi")),
            ],
        ),
        migrations.CreateModel(
            name='TalimTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name="Ta'lim turi nomi")),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name="Ta'lim shakli nomi")),
                ('kontrakt_narxi', models.CharField(max_length=455, verbose_name='Kontrakt narxi')),
                ('shartnoma_seriyasi', models.CharField(max_length=255, verbose_name='Shartnoma seriyasi')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.filial')),
                ('talim_shakli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.talimshakli')),
                ('talim_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.talimturi')),
            ],
        ),
    ]
