# Generated by Django 5.0.4 on 2024-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yonalish',
            name='nomi',
            field=models.CharField(max_length=100, verbose_name="Yo'nalish nomi"),
        ),
    ]
