# Generated by Django 5.0.4 on 2024-04-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_alter_yonalish_nomi'),
    ]

    operations = [
        migrations.AddField(
            model_name='yonalish',
            name='oqish_muddati',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yonalish',
            name='yonalish_kodi',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
