# Generated by Django 5.0.4 on 2024-04-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_yonalish_oqish_muddati_yonalish_yonalish_kodi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yonalish',
            name='nomi',
            field=models.CharField(max_length=200, verbose_name="Yo'nalish nomi"),
        ),
    ]
