# Generated by Django 5.0.4 on 2024-04-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0004_alter_yonalish_nomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterSlayder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='register-slayder/')),
                ('title', models.CharField(max_length=455)),
                ('body', models.TextField()),
                ('button_text', models.CharField(max_length=455)),
            ],
        ),
    ]
