# Generated by Django 5.0.4 on 2024-04-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0002_eskizbearertoken_delete_eskizauthemailandtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EskizEmailAndPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.TextField()),
            ],
        ),
    ]
