# Generated by Django 5.0.4 on 2024-04-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0003_eskizemailandpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
