# Generated by Django 5.0.4 on 2024-04-21 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_app', '0002_alter_application_is_perevod'),
        ('shartnoma_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shartnoma',
            options={'verbose_name': 'Shartnoma', 'verbose_name_plural': 'Shartnomalar'},
        ),
        migrations.RemoveField(
            model_name='shartnoma',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply_app.application', verbose_name='Ariza'),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='shartnoma_fayl',
            field=models.FileField(blank=True, null=True, upload_to='shartnomalar/', verbose_name='Shartnoma fayli'),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti'),
        ),
        migrations.AlterField(
            model_name='shartnoma',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
