# Generated by Django 5.0.4 on 2024-04-22 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply_app', '0002_alter_application_is_perevod'),
        ('shartnoma_app', '0003_alter_shartnoma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shartnoma',
            name='apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shartnoma', to='apply_app.application', verbose_name='Ariza'),
        ),
    ]
